apiVersion: v1
kind: Pod
metadata:
  name: kinit-dbapp
spec:
  containers:
  - image: acraccess.azurecr.io/kinit-sidecar:1.0 
    imagePullPolicy: Always
    name: kinit
    resources:
      limits: 
        memory: "256Mi"
        cpu: "500m"   
      requests: 
        memory: "256Mi"
        cpu: "500m"   
    env:
      - name: PERIOD_SECONDS
        value: "10"
      - name: OPTIONS
        value: -k dbuser@ENEROSORG.ONMICROSOFT.COM
    volumeMounts:
      - name: ccache
        mountPath: /dev/shm
      - name: krb5-config
        mountPath: /etc/krb5.conf
        subPath: krb5.conf
     # - name: keytab-vol  
     #   mountPath: /krb5/dbuser.keytab
     #   subPath: dbuser.keytab
      - name: keytab-vol-csi
        mountPath: /krb5
        readOnly: true

  - image: acraccess.azurecr.io/sql-kerberos:1.0
    imagePullPolicy: Always
    name: dbapp
    resources:
      limits: 
        memory: "256Mi"
        cpu: "500m"   
      requests: 
        memory: "256Mi"
        cpu: "500m"      
    envFrom:
    - configMapRef:
        name: dbconfig
        
    volumeMounts:
      - name: ccache
        mountPath: /dev/shm
      - name: krb5-config
        mountPath: /etc/krb5.conf
        subPath: krb5.conf
      - name: keytab-vol-csi
        mountPath: /krb5
        readOnly: true  
        
  volumes:
    - name: ccache
      emptyDir: {}
     
    - name: krb5-config
      configMap:
        name: krb5config
        items:
          - key: krb5.conf
            path: krb5.conf

    - name: keytab-vol-csi
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kv-secretprovider"
